### PR TITLE
feat: Use py3createtorrent as module, not just as cli tool

### LINKED ISSUE #13: Support for usage as a module
py3createtorrent can as of now only be used as a CLI tool but it'd be super useful if it exposed methods to use from other python modules.

### PR DESCRIPTION
**Pull request by ToasterUwU**
It will need a bunch of refactoring, but i will make it happen.

Fixes #13

### CODE REVIEW

**Comment by ToasterUwU** [comment]
Ok, i have time, but no brain juices for today. 
I will start actually working on it tommorow.

**Comment by ToasterUwU** [comment]
Sorry about bailing on the thing I said. 
I had a bad migraine and then got busy with other stuff.

I know I don't technically have to do this, but I said I would, so I wanna keep my word and follow up on the things I say.

I will not have time today or tomorrow. But on Sunday I should have some time.

**Comment by rsnitsch** [comment]
No pressure. Please feel completely free to do this whenever you want - or to don't do this at all. There is zero obligation. Coding is supposed to be fun, especially when its unpaid.

**Comment by ToasterUwU** [comment]
Im back. Was busy with life sadly.

Will work on this a bit now, and whenever I get some more time here and there.

**Comment by ToasterUwU** [comment]
lol that was a fix, not a feat.. Brain lag I guess

**Comment by ToasterUwU** [comment]
@rsnitsch I think im pretty much done. Im gonna test it, but i recommend you do as well. "4 Augen sehen mehr als 2"

**Comment by ToasterUwU** [comment]
Tested every single option with module and cli use. So it should be fine, but test yourself to be save like I said.

If you feel comfortable with pressing that green button, go right ahead and release the new version on pypi. 
A little mention in the github release about my work would make me very happy.

**Comment by rsnitsch** [comment]
Thank you very much. Next 2 weeks I have no time, unfortunately, but then I'll review and merge it. Of course you will be mentioned in the release/changelog.

**Comment by ToasterUwU** [comment]
Just as a self reminder: Need to update the "if _parser" checks so they are explicit and only ever react to None

**Comment by ToasterUwU** [comment]
@rsnitsch Hey, I know you are a busy person, I just wanna make sure you wont forget.

**Comment by rsnitsch** [comment]
Sorry that it takes longer than estimated. I did not forget. I am currently impeded by stuff outside of my control. But it will happen this month.

**Comment by rsnitsch** [comment]
The trailing commas are back, but I saw you wrote that yapf is adding them back. In this case they can stay. I'll try to improve the yapf configuration later, if possible.

Other than that, PR looks fine. The only thing I would add is that py3createtorrent should use a custom Exception type. But that can be done later as well.

Thank you very much for your work, of course you will be mentioned in the next release.

> @fakerybakery Hi, can we switch from GPL to LGPL if this is going to be a library?

@ToasterUwU @cpurules Do you agree changing the license to LGPL?

**Comment by ToasterUwU** [comment]
> The trailing commas are back, but I saw you wrote that yapf is adding them back. In this case they can stay. I'll try to improve the yapf configuration later, if possible.
> 
> Other than that, PR looks fine. The only thing I would add is that py3createtorrent should use a custom Exception type. But that can be done later as well.
> 
> Thank you very much for your work, of course you will be mentioned in the next release.
> 
> > @fakerybakery Hi, can we switch from GPL to LGPL if this is going to be a library?
> 
> @ToasterUwU @cpurules Do you agree changing the license to LGPL?

Very nice.

And yes, I support switching to LGPL.

**Comment by cpurules** [comment]
No issue from me with the license switch!

**Comment by ToasterUwU** [comment]
@rsnitsch Hey, so everyone needed agreed to LGPL, the feature is merged, so why is there no new release for this yet?

**Comment by rsnitsch** [comment]
> @rsnitsch Hey, so everyone needed agreed to LGPL, the feature is merged, so why is there no new release for this yet?

It will happen soon.

**Comment by rsnitsch** [comment]
@ToasterUwU The new release v1.2.0 has now been published: https://github.com/rsnitsch/py3createtorrent/releases/tag/v1.2.0

**Pull request merged**
